### ISSUE TITLE
init ML/DP

### ISSUE THREAD

**Issue by r0bertgabriel** [Hiarleyy/Ns-3-simulations#35]
Fase de pesquisa sobre modelos

**Parâmetros:**

Provavelmente, e o algoritmo vai ter que fazer é mudar o vetor velocidade
 considerando um cenário que todos saem da mesma posição, tanto antes, como depois da otimização
 porém, com a melhor trajetória. Acredito que para isso, o algoritmo tenha que ser capaz de identificar a direção das antenas e depois levar em consideração o número de usuário por antena ( estáticas) para ai sim, fazer uma recomendação, em uma planilha, das melhores posições.

**Comment by Hiarleyy** [comment]
- [ ] criando um modelo ficticio para estudar um modelo de ia possivel de ser utilizado
- [ ] testar modelo do gpt 
- [ ] Checar o MSE do modelo (indice de validação)
